name: 'Build'

on:
  pull_request:
  push:
    branches:
      - 'development'
      - 'master'
      - 'release/**'

jobs:
  build:
    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.1.0
      - name: 'Setup JDK'
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 11
          distribution: temurin
      - name: 'Setup Android SDK'
        uses: android-actions/setup-android@v2.0.2
      - name: 'Assemble'
        run: ./gradlew --no-daemon assembleDebug
      - name: 'Detekt'
        run: ./gradlew --no-daemon detektDebug
      - name: 'Upload Detekt Report Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: 'Detekt Results'
          path: |
            **/build/reports/detekt/*.md
      - name: 'Android Lint'
        run: ./gradlew --no-daemon lintDebug
      - name: 'Upload Lint Report Artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: 'Lint Results'
          path: | 
            **/build/reports/lint/*.html
